from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startLesson = QtWidgets.QPushButton(self.centralwidget)
        self.startLesson.setGeometry(QtCore.QRect(60, 660, 131, 41))
        self.startLesson.setObjectName("startLesson")
        self.endLesson1 = QtWidgets.QPushButton(self.centralwidget)
        self.endLesson1.setGeometry(QtCore.QRect(260,660, 131, 41))
        self.endLesson1.setObjectName("endLesson")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 630, 510))
        self.label.setObjectName("label")
        self.happyLabel = QtWidgets.QLabel(self.centralwidget)
        self.happyLabel.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.happyLabel.setObjectName("happyLabel")
        self.sadLabel = QtWidgets.QLabel(self.centralwidget)
        self.sadLabel.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.sadLabel.setObjectName("sadLabel")
        self.angryLabel = QtWidgets.QLabel(self.centralwidget)
        self.angryLabel.setGeometry(QtCore.QRect(10, 70, 67, 17))
        self.angryLabel.setObjectName("angryLabel")
        self.scaredLabel = QtWidgets.QLabel(self.centralwidget)
        self.scaredLabel.setGeometry(QtCore.QRect(240, 10, 67, 17))
        self.scaredLabel.setObjectName("scaredLabel")
        self.suprisedLabel = QtWidgets.QLabel(self.centralwidget)
        self.suprisedLabel.setGeometry(QtCore.QRect(240, 40, 67, 17))
        self.suprisedLabel.setObjectName("suprisedLabel")
        
        self.neutralLabel = QtWidgets.QLabel(self.centralwidget)
        self.neutralLabel.setGeometry(QtCore.QRect(240, 70, 67, 17))
        self.neutralLabel.setObjectName("neutralLabel")
        self.happyRate = QtWidgets.QLabel(self.centralwidget)
        self.happyRate.setGeometry(QtCore.QRect(70, 10, 67, 17))
        self.happyRate.setTextFormat(QtCore.Qt.AutoText)
        self.happyRate.setObjectName("happyRate")
        self.sadRate = QtWidgets.QLabel(self.centralwidget)
        self.sadRate.setGeometry(QtCore.QRect(70, 40, 67, 17))
        self.sadRate.setObjectName("sadRate")
        self.angryRate = QtWidgets.QLabel(self.centralwidget)
        self.angryRate.setGeometry(QtCore.QRect(70, 70, 67, 17))
        self.angryRate.setObjectName("angryRate")
        self.scaredRate = QtWidgets.QLabel(self.centralwidget)
        self.scaredRate.setGeometry(QtCore.QRect(320, 10, 67, 17))
        self.scaredRate.setObjectName("scaredRate")
        self.suprisedRate = QtWidgets.QLabel(self.centralwidget)
        self.suprisedRate.setGeometry(QtCore.QRect(320, 40, 67, 17))
        self.suprisedRate.setObjectName("suprisedRate")
        self.neutralRate = QtWidgets.QLabel(self.centralwidget)
        self.neutralRate.setGeometry(QtCore.QRect(320, 70, 67, 17))
        self.neutralRate.setObjectName("neutralRate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 760, 481, 17))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Class V 1.0"))
        self.startLesson.setText(_translate("MainWindow", "Dersi Başlat"))
        self.endLesson1.setText(_translate("MainWindow", "Dersi Bitir"))
        self.label.setText(_translate("MainWindow", "Camera"))
        self.happyLabel.setText(_translate("MainWindow", "Happy:"))
        self.sadLabel.setText(_translate("MainWindow", "Sad:"))
        self.angryLabel.setText(_translate("MainWindow", "Angry:"))
        self.scaredLabel.setText(_translate("MainWindow", "Scared:"))
        self.suprisedLabel.setText(_translate("MainWindow", "Suprised:"))
        self.neutralLabel.setText(_translate("MainWindow", "Neutral:"))
        self.happyRate.setText(_translate("MainWindow", "%"))
        self.sadRate.setText(_translate("MainWindow", "%"))
        self.angryRate.setText(_translate("MainWindow", "%"))
        self.scaredRate.setText(_translate("MainWindow", "%"))
        self.suprisedRate.setText(_translate("MainWindow", "%"))
        self.neutralRate.setText(_translate("MainWindow", "%"))
        self.label_2.setText(_translate("MainWindow", "Copyright ® Baran Bayazıt & Furkan Kaya"))

